name: lad
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pandas==1.4.4
  - spacy==3.3.1 
  - tqdm
    #spacy-transformers
    #python -m spacy download en_core_web_trf
    #python -m spacy download en_core_web_sm
  - gensim==4.* 
  - matplotlib
  - nltk==3.7
  - pip:
    - pyLDAvis
    - pytrec-eval-terrier==0.5.2
