name: lady
channels:
  - conda-forge
  - pytorch
  - nvidia
#  - anaconda
  - defaults
dependencies:
  - pandas==1.4.4
  - spacy==3.3.1 
    #spacy-transformers
    #python -m spacy download en_core_web_trf
    #python -m spacy download en_core_web_sm
  - tqdm
  - transformers==4.26.1 #needed if augmentation via backtranslation
  - pytorch==1.13.1
#  - gensim==4.*
#  - matplotlib
#  - nltk==3.7
#  - pip:
#    - pyLDAvis
#    - pytrec-eval-terrier==0.5.2
#    - bitermplus==0.6.10 #install it if you want to use btm model in the topic modeling layer
#    - seaborn==0.12.2
#    - simalign==0.3
